### PR TITLE
➕ Add phaser

### LINKED ISSUE #19: Add phaser
- Install phaser with: npm install phaser

### PR DESCRIPTION
**Pull request by cboenke**
Closes #19

### CODE REVIEW

**Review by JuKahl — APPROVED** [review]
GJ 🍝

**Review by sweisz — APPROVED** [review]
GJ ⚒️

**Review by phlgr — APPROVED** [review]
GJ 🚀

**Review by mewiemers — COMMENTED** [review]
Lets start the game ! GJ! 🐭

**Review by DNaunin — APPROVED** [review]
GJ! 👍🏻

**Review by mrana17 — APPROVED** [review]
GJ 👍

**Pull request merged**
